resolver: lts-10.4
packages:
  - composite-aeson
  - composite-aeson-refined
  - composite-base
  - composite-ekg
  - composite-opaleye
  - example
extra-deps: []
# nix:
#   enable: true
#   packages:
#     - postgresql
#     - zlib
flags: {}
extra-package-dbs: []
